# This file will manage all Tesla functions and data import

import discord, teslapy, json

def loginToTeslaAccount(email): 
    print("\t\t-=-=-= Tesla Login Prompt =-=-=-\n")
    #Gather input from discord
    input = ""

    #check if valid email # github autogenerated code
    # needs to take input from discord though
    while not input.endswith("@gmail.com"):
        input = input("Enter your email: ")
        if not input.endswith("@gmail.com"):
            print("Invalid email. Please try again.")

    #Use it as tesla URL for prompt
    tesla = teslapy.Tesla(input)
    if not tesla.authorized:
        #print('Open this URL: ' + tesla.authorization_url())
        tesla.fetch_token(authorization_response=input('Enter URL after authentication: '))
            #if tesla.authorized:
                #print('Successful login.')
